apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf2.4-app
  labels:
    app: tf001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf001
  template:
    metadata:
      labels:
        app: tf001
    spec:
      containers:
      - name: tf001
        #image: tensorflow/tensorflow:latest-gpu-py3-jupyter
        image: yenaing/mytensorflow2.4-gpu-jupyter
        ports:
        - containerPort: 8888
        - containerPort: 6006
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostvol
          mountPath: /notebooks
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            # PVC name you created
            claimName: tf-pvc
      nodeSelector:
        accelerator: nvidia-gt710
