apiVersion: v1
kind: PersistentVolume
metadata:
  # any PV name
  name: tf-pv
spec:
  storageClassName: tf001
  capacity:
    # storage size
    storage: 100Gi
  accessModes:
    # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    # retain even if pods terminate
    Retain
  nfs:
    # NFS server's definition
    path: /mnt/tensorflow
    server: 192.168.14.10
    readOnly: false
